/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ahorrofamiliar.views;

import com.ahorrofamiliar.dao.UsuarioDAO;
import com.ahorrofamiliar.models.Usuario;
import java.awt.Point;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alondra
 */
public class BusUsuario extends javax.swing.JFrame {

    /**
     * Creates new form BusUsuario
     */
    public BusUsuario() {
        initComponents();
        LLenarTabla();
    }
    UsuarioDAO c = new UsuarioDAO();
    public static String accionx;
    public static String IdRol;
    public static String nombre;
    public static String apellido;
    public static String TipoIdDoc;
    public static String NumDoc;
    public static String sexo;
    public static String situacion;
    
    public void LLenarTabla(){
        List<Usuario> list = new ArrayList();
        list = c.ListarUsuario(jtnombre.getText(), jtapellido.getText());

        DefaultTableModel modelo = new DefaultTableModel();
        String[] columnNames = {"Id","Rol", "Nombre", "Apellido", "Tipo_Documento", "Numero_doc", "sexo", "Situacion"};
        modelo.setColumnIdentifiers(columnNames);
        Object[] fila = new Object[modelo.getColumnCount()];
        for (int i = 0; i < list.size(); i++) {
            fila[0] = list.get(i).getId();
            fila[1] = list.get(i).getRol();
            fila[2] = list.get(i).getNombre();
            fila[3] = list.get(i).getApellido();
            fila[4] = list.get(i).getTipoDocumento();
            fila[5] = list.get(i).getNumeroDocumento();
            fila[6] = list.get(i).getSexo();
            fila[7] = list.get(i).getSituacion();
            modelo.addRow(fila);//agregamos una fila a nuestro modelo de tabla
        }

        jtBusqueda.setModel(modelo);
        jtBusqueda.getColumnModel().getColumn(7).setMaxWidth(0);
        jtBusqueda.getColumnModel().getColumn(7).setMinWidth(0);
        jtBusqueda.getTableHeader().getColumnModel().getColumn(7).setMaxWidth(0);
        jtBusqueda.getTableHeader().getColumnModel().getColumn(7).setMinWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtnombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtapellido = new javax.swing.JTextField();
        jtBuscar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtBusqueda = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jbRegistrar = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(255, 51, 51));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("X");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 6, 40, -1));

        jLabel2.setText("Nombre:");

        jLabel1.setText("Apellidos:");

        jtBuscar.setText("Buscar");
        jtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtBuscar))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 640, 80));

        jtBusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Rol", "Nombre", "Apellido", "Tipo_Documento", "Numero_doc", "sexo", "Situacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtBusquedaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtBusquedaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtBusqueda);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 640, 320));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, -1));

        jbRegistrar.setText("Registrar");
        jbRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(jbRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, -1, -1));

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });
        jPanel1.add(jbModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, -1, -1));

        jbEliminar.setText("Eiminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jbEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 6, 680, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBuscarActionPerformed
        // TODO add your handling code here:
        LLenarTabla();

    }//GEN-LAST:event_jtBuscarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        boolean result = false;
        int Id = Integer.parseInt(accionx);
        c.anular(Id, "I");//actualiza a inactivo
        JOptionPane.showMessageDialog(null, "Se Elimino el registro.");
        LLenarTabla();
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jtBusquedaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtBusquedaMousePressed
        // TODO add your handling code here:
        JTable table = (JTable) evt.getSource();
        Point point_ = evt.getPoint();
        int row = table.rowAtPoint(point_);
        if (evt.getClickCount() == 1) {
            accionx = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 0).toString();//id
            IdRol = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 1).toString();
            nombre = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 2).toString();
            apellido = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 3).toString();
            TipoIdDoc = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 4).toString();
            NumDoc = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 5).toString();
            sexo = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 6).toString();
            situacion = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 7).toString();
        } else {
            accionx = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 0).toString();//id
            IdRol = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 1).toString();
            nombre = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 2).toString();
            apellido = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 3).toString();
            TipoIdDoc = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 4).toString();
            NumDoc = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 5).toString();
            sexo = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 6).toString();
            situacion = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 7).toString();
        }
    }//GEN-LAST:event_jtBusquedaMousePressed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        // TODO add your handling code here:
        try {
            if (accionx.equals("0")) {
                JOptionPane.showMessageDialog(null, "Debe seleccionar un registro");
            } else {
                DetUsuario entrar = new DetUsuario();
                entrar.setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro");
        }
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistrarActionPerformed
        // TODO add your handling code here:
        accionx = "0";
        nombre = "";
        apellido = "";
        TipoIdDoc = "";
        NumDoc = "";
        sexo = "";
        situacion = "";
        DetUsuario detusuario = new DetUsuario();
        detusuario.setVisible(true);
    }//GEN-LAST:event_jbRegistrarActionPerformed

    private void jtBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtBusquedaMouseClicked
        // TODO add your handling code here:}
        JTable table = (JTable) evt.getSource();
        Point point_ = evt.getPoint();
        int row = table.rowAtPoint(point_);
        if (evt.getClickCount() == 1) {
            accionx = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 0).toString();//id
            IdRol = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 1).toString();
            nombre = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 2).toString();
            apellido = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 3).toString();
            TipoIdDoc = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 4).toString();
            NumDoc = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 5).toString();
            sexo = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 6).toString();
            situacion = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 7).toString();
        } else {
            accionx = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 0).toString();//id
            IdRol = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 1).toString();
            nombre = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 2).toString();
            apellido = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 3).toString();
            TipoIdDoc = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 4).toString();
            NumDoc = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 5).toString();
            sexo = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 6).toString();
            situacion = jtBusqueda.getValueAt(jtBusqueda.getSelectedRow(), 7).toString();
        }
    }//GEN-LAST:event_jtBusquedaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbRegistrar;
    private javax.swing.JButton jtBuscar;
    private javax.swing.JTable jtBusqueda;
    private javax.swing.JTextField jtapellido;
    private javax.swing.JTextField jtnombre;
    // End of variables declaration//GEN-END:variables
}
