/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ahorrofamiliar.views;

import com.ahorrofamiliar.models.Meta;
import com.ahorrofamiliar.dao.UsuarioDAO;
import com.ahorrofamiliar.dao.MetaDAO;
import com.ahorrofamiliar.models.Usuario;
import com.ahorrofamiliar.service.MetaAporteService;
import com.ahorrofamiliar.models.MetaAporte;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Alondra
 */
public class DetMetaAporte extends javax.swing.JFrame {

    private MetaAporteService metaAporteService = new MetaAporteService();
    private MetaDAO metaDAO = new MetaDAO();
    private UsuarioDAO usuarioDAO = new UsuarioDAO();
    private int idAporteActual = -1; // -1 indica que es un nuevo aporte

// Usas estos para listar y llenar combos
    /**
     * Creates new form DetUsuario
     */
    public DetMetaAporte() {
        initComponents();
        cargarCombos(); // Cargar combos al iniciar
        agregarEventos(); // Agregar eventos a botones
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtAporteReal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbMeta = new javax.swing.JComboBox<>();
        cbUsuario = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        dateFechaRegistro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btguardar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtAporteEstimado = new javax.swing.JTextField();
        situacion = new javax.swing.JTextField();
        btSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Detalle Meta Aporte");

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Aporte Real");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));
        jPanel2.add(txtAporteReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 120, 30));

        jLabel3.setText("Usuario");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, 20));

        jLabel4.setText("Meta");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jPanel2.add(cbMeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 130, -1));

        cbUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(cbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 140, -1));

        jLabel6.setText("Fecha de registro");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));
        jPanel2.add(dateFechaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 90, -1));

        jLabel7.setText("SItuacion");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 80, -1));

        btguardar.setText("Guardar");
        jPanel2.add(btguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 100, -1));

        jLabel8.setText("AporteEstimado");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        txtAporteEstimado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAporteEstimadoActionPerformed(evt);
            }
        });
        jPanel2.add(txtAporteEstimado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 90, -1));
        jPanel2.add(situacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 20, -1));

        btSalir.setBackground(new java.awt.Color(255, 51, 51));
        btSalir.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btSalir.setForeground(new java.awt.Color(255, 255, 255));
        btSalir.setText("X");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(163, 163, 163)
                        .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUsuarioActionPerformed

    private void txtAporteEstimadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAporteEstimadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAporteEstimadoActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetMetaAporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetMetaAporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetMetaAporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetMetaAporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetMetaAporte().setVisible(true);
            }
        });
    }

    private void cargarCombos() {
        try {
            List<Meta> metas = metaDAO.listarMetas();
            cbMeta.removeAllItems();
            for (Meta meta : metas) {
                cbMeta.addItem(meta);
            }

            List<Usuario> usuarios = usuarioDAO.listarUsuarios();
            cbUsuario.removeAllItems();
            for (Usuario usuario : usuarios) {
                cbUsuario.addItem(usuario);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar combos: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void agregarEventos() {
        btguardar.addActionListener(evt -> guardarAporte());
        btSalir.addActionListener(evt -> this.dispose());
    }

    private void guardarAporte() {
        try {
            Meta metaSeleccionada = (Meta) cbMeta.getSelectedItem();
            Usuario usuarioSeleccionado = (Usuario) cbUsuario.getSelectedItem();

            if (metaSeleccionada == null) {
                JOptionPane.showMessageDialog(this, "Seleccione una meta.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (usuarioSeleccionado == null) {
                JOptionPane.showMessageDialog(this, "Seleccione un usuario.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            double aporteEstimado = Double.parseDouble(txtAporteEstimado.getText().trim());
            double aporteReal = Double.parseDouble(txtAporteReal.getText().trim());

            String fechaStr = dateFechaRegistro.getText().trim();
            if (fechaStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese la fecha de registro.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            Date fechaRegistro = formato.parse(fechaStr);

            String situacionStr = situacion.getText().trim();
            if (situacionStr.isEmpty()) {
                situacionStr = "ACT"; // Valor por defecto
            }

            MetaAporte aporte = new MetaAporte();
            aporte.setIdMeta(metaSeleccionada.getId());
            aporte.setIdUsuario(usuarioSeleccionado.getId());
            aporte.setAporteEstimado(aporteEstimado);
            aporte.setAporteReal(aporteReal);
            aporte.setFechaRegistro(fechaRegistro);
            aporte.setSituacion(situacionStr);

            if (idAporteActual == -1) {
                // Insertar nuevo aporte
                metaAporteService.insertarAporte(aporte);
                JOptionPane.showMessageDialog(this, "Aporte guardado correctamente.");
            } else {
                // Modificar aporte existente
                aporte.setId(idAporteActual);
                metaAporteService.modificarAporte(aporte);
                JOptionPane.showMessageDialog(this, "Aporte modificado correctamente.");
            }

            limpiarCampos();
            idAporteActual = -1; // Resetear

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese valores numéricos válidos para aportes.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use yyyy-MM-dd.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar aporte: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpiarCampos() {
        txtAporteEstimado.setText("");
        txtAporteReal.setText("");
        dateFechaRegistro.setText("");
        situacion.setText("ACT");
        cbMeta.setSelectedIndex(-1);
        cbUsuario.setSelectedIndex(-1);
    }



    public void cargarDatosEnFormulario(int idAporte) {
        try {
            MetaAporte aporte = metaAporteService.buscarPorId(idAporte);
            if (aporte != null) {
                // Guardar el ID para saber que estamos modificando
                idAporteActual = aporte.getId();

                // Seleccionar la Meta en el combo
                seleccionarComboPorId(cbMeta, aporte.getIdMeta());

                // Seleccionar el Usuario en el combo
                seleccionarComboPorId(cbUsuario, aporte.getIdUsuario());

                // Llenar los campos de texto con los datos
                txtAporteEstimado.setText(String.valueOf(aporte.getAporteEstimado()));
                txtAporteReal.setText(String.valueOf(aporte.getAporteReal()));

                // Formatear y mostrar la fecha
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                dateFechaRegistro.setText(sdf.format(aporte.getFechaRegistro()));

                situacion.setText(aporte.getSituacion());
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el aporte con ID: " + idAporte, "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar datos del aporte: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void seleccionarComboPorId(JComboBox<?> combo, int id) {
        for (int i = 0; i < combo.getItemCount(); i++) {
            Object item = combo.getItemAt(i);
            if (item instanceof Meta && ((Meta) item).getId() == id) {
                combo.setSelectedIndex(i);
                break;
            } else if (item instanceof Usuario && ((Usuario) item).getId() == id) {
                combo.setSelectedIndex(i);
                break;
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalir;
    private javax.swing.JButton btguardar;
    private javax.swing.JComboBox<Meta> cbMeta;
    private javax.swing.JComboBox<Usuario> cbUsuario;
    private javax.swing.JTextField dateFechaRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField situacion;
    private javax.swing.JTextField txtAporteEstimado;
    private javax.swing.JTextField txtAporteReal;
    // End of variables declaration//GEN-END:variables
}
