/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ahorrofamiliar.views;

import com.ahorrofamiliar.dao.UsuarioDAO;
import com.ahorrofamiliar.dao.Utilitario;
import com.ahorrofamiliar.models.Usuario;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Alondra
 */
public class DetUsuario extends javax.swing.JFrame {

    /**
     * Creates new form DetUsuario
     */
    UsuarioDAO c = new UsuarioDAO();
    Utilitario util = new Utilitario();
    public static String accionx;
    public static String IdRol;
    public static String nombre;
    public static String apellido;
    public static String TipoIdDoc;
    public static String NumDoc;
    public static String sexo;
    public static String situacion;

    public DetUsuario() {
        initComponents();
        IniciarFormularios();
    }

    public void IniciarFormularios() {
        accionx = BusUsuario.accionx;
        jcTipodoc.removeAllItems();
        jcRol.removeAllItems();
        util.RellenarComboBox("tipo_documento", "Nombre", jcTipodoc);
        util.RellenarComboBox("rol", "Nombre", jcRol);
        jtnombre.setText("");
        jtapellido.setText("");
        jtnumdoc.setText("");
        jtsexo.setText("");
        jtsituacion.setText("");
        if (accionx.equals("0")) {
            jtid.setText("0");
        } else {

            IdRol = BusUsuario.IdRol;
            nombre = BusUsuario.nombre;
            apellido = BusUsuario.apellido;
            TipoIdDoc = BusUsuario.TipoIdDoc;
            NumDoc = BusUsuario.NumDoc;
            sexo = BusUsuario.sexo;
            situacion = BusUsuario.situacion;
            jtid.setText(accionx);

            jtnombre.setText(nombre);
            jtapellido.setText(apellido);
            jtnumdoc.setText(NumDoc);
            jtsexo.setText(sexo);
            jtsituacion.setText(situacion);

            jcRol.setSelectedItem(IdRol);
            jcTipodoc.setSelectedItem(TipoIdDoc);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtapellido = new javax.swing.JTextField();
        jcRol = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jcTipodoc = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jtsexo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtsituacion = new javax.swing.JTextField();
        btguardar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtnumdoc = new javax.swing.JTextField();
        jtid = new javax.swing.JTextField();
        btSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Detalle Usuario");

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 20));
        jPanel2.add(jtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 120, -1));

        jLabel3.setText("Apellido");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel4.setText("Rol");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 20, 20));
        jPanel2.add(jtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 120, -1));

        jcRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jcRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 120, -1));

        jLabel5.setText("Tipo Doc");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 50, 20));

        jcTipodoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jcTipodoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 110, -1));

        jLabel6.setText("Sexo");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));
        jPanel2.add(jtsexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 40, -1));

        jLabel7.setText("SItuacion");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 50, -1));

        jtsituacion.setText("A");
        jPanel2.add(jtsituacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 50, -1));

        btguardar.setText("Guardar");
        btguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btguardarActionPerformed(evt);
            }
        });
        jPanel2.add(btguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 100, -1));

        jLabel8.setText("Num Doc");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        jPanel2.add(jtnumdoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 90, -1));
        jPanel2.add(jtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 140, 70, -1));

        btSalir.setBackground(new java.awt.Color(255, 51, 51));
        btSalir.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btSalir.setForeground(new java.awt.Color(255, 255, 255));
        btSalir.setText("X");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btSalir))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btSalirActionPerformed

    private void btguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btguardarActionPerformed
        // TODO add your handling code here:
        UsuarioDAO cm = new UsuarioDAO();
        Usuario usu = new Usuario();
        Usuario val = new Usuario();
        val = c.ValporDNI(jcTipodoc.getSelectedItem().toString(), jtnumdoc.getText());
        if (val != null) {
            JOptionPane.showMessageDialog(null, "El usuario ya existe.");
        } else {
            usu.setId(Integer.parseInt(jtid.getText()));
            usu.setNombre(jtnombre.getText());
            usu.setApellido(jtapellido.getText());
            int rol = jcRol.getSelectedIndex();
            int tipo_doc = jcTipodoc.getSelectedIndex();
            usu.setIdRol(rol);
            usu.setId_tip_doc(tipo_doc);
            usu.setNumeroDocumento(jtnumdoc.getText());
            usu.setSexo(jtsexo.getText());
            usu.setSituacion(jtsituacion.getText());
            if (usu.getId() == 0) {
                cm.adicion(usu);
            } else {
                cm.modifica(usu);
            }
            JOptionPane.showMessageDialog(null, "Se guardaron los datos.");
            dispose();
        }

    }//GEN-LAST:event_btguardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalir;
    private javax.swing.JButton btguardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jcRol;
    private javax.swing.JComboBox<String> jcTipodoc;
    private javax.swing.JTextField jtapellido;
    private javax.swing.JTextField jtid;
    private javax.swing.JTextField jtnombre;
    private javax.swing.JTextField jtnumdoc;
    private javax.swing.JTextField jtsexo;
    private javax.swing.JTextField jtsituacion;
    // End of variables declaration//GEN-END:variables
}
